# Generated by Django 5.2.17 on 2026-09-21 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('MONTHLY', '월 합계형'), ('PROJECT', '프로젝트별형')], max_length=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('metric_key', models.CharField(blank=True, choices=[('REVENUE', '매출액'), ('MATERIAL_COST', '재료비'), ('LABOR_COST', '노무비'), ('EXPENSE_COST', '경비'), ('SGA_EXPENSE', '판매관리비'), ('PURCHASE_AMOUNT', '매입액'), ('COLLECTION_AMOUNT', '수금액'), ('RECEIVABLE_BALANCE', '미수금 잔액'), ('CASH_BALANCE', '현금 잔액'), ('PRODUCTION_QTY', '생산량'), ('PRODUCTION_CAPACITY', '생산 능력'), ('HEADCOUNT', '인원수'), ('ORDER_RECEIVED', '신규 수주액'), ('ORDER_BACKLOG', '수주 잔고'), ('PIPELINE_AMOUNT', '파이프라인 금액'), ('PIPELINE_WIN_RATE', '예상 수주 확률')], max_length=30, null=True)),
                ('help_text', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='organization.department')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('department', 'name'), name='unique_active_item_name_per_department')],
            },
        ),
    ]
