# Generated by Django 5.2.17 on 2026-09-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('metric_key', models.CharField(choices=[('REVENUE', '매출액'), ('OPERATING_MARGIN', '영업이익률'), ('UTILIZATION', '가동률'), ('PRODUCTION_QTY', '생산량'), ('ORDER_RECEIVED', '신규 수주액')], max_length=30)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'metric_key'), name='unique_goal_per_year_metric')],
            },
        ),
    ]
